spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/<YOUR-TENANT-ID-GOES-HERE>/v2.0
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
            client-id: <YOUR CLIENT ID>
            client-secret: <YOUR CLIENT SECRET>
            scope:
              - openid
              - email
              - profile
